### ISSUE TITLE
Long error when installing

### ISSUE THREAD

**Issue by ivan-avalos** [adbenitez/deltachat-cursed#22]
¡Hola, adb! I always get an error when trying to install this thing. The error is not really descriptive to me, I'd appreciate if you took the time to read the backtrace and see if there's something wrong with the program or it's just me.

```
Running deltachat-1.51.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-qxmpkkkh/deltachat-1.51.0/egg-dist-tmp-wwxna787
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-qxmpkkkh/deltachat-1.51.0/setup.py", line 42, in <module>
    "Development Status :: 4 - Beta",
  File "/tmp/easy_install-qxmpkkkh/deltachat-1.51.0/setup.py", line 9, in main
    MODULE_NAME = "deltachat_cursed"
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 455, in __init__
    _Distribution.__init__(self, {
  File "/usr/lib/python3.9/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 801, in finalize_options
    ep(self)
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 808, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/usr/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/usr/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 57, in add_cffi_module
    ffi = ffi()      # maybe it's a function instead of directly an ffi
  File "src/deltachat/_build.py", line 176, in ffibuilder
  File "src/deltachat/_build.py", line 41, in local_build_flags
AssertionError: ['/tmp/easy_install-qxmpkkkh/target/release/libdeltachat.a']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/avalos/Downloads/deltachat-cursed/setup.py", line 29, in <module>
    setup(
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.9/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3.9/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/usr/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 408, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 650, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 697, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 744, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
    dist = best[req.key] = env.best_match(
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
    return installer(requirement)
  File "/usr/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 669, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 1162, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 1146, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 257, in run_setup
    raise
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 164, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 139, in resume
    raise exc.with_traceback(self._tb)
  File "/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-qxmpkkkh/deltachat-1.51.0/setup.py", line 42, in <module>
    "Development Status :: 4 - Beta",
  File "/tmp/easy_install-qxmpkkkh/deltachat-1.51.0/setup.py", line 9, in main
    MODULE_NAME = "deltachat_cursed"
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 455, in __init__
    _Distribution.__init__(self, {
  File "/usr/lib/python3.9/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 801, in finalize_options
    ep(self)
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 808, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/usr/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/usr/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 57, in add_cffi_module
    ffi = ffi()      # maybe it's a function instead of directly an ffi
  File "src/deltachat/_build.py", line 176, in ffibuilder
  File "src/deltachat/_build.py", line 41, in local_build_flags
AssertionError: ['/tmp/easy_install-qxmpkkkh/target/release/libdeltachat.a']
```

**Comment by adbenitez** [comment]
hi, I need more info, what system you are using, what architecture? python version? the error seems to be that there are not deltachat wheels available for your system.

**Comment by ivan-avalos** [comment]
* **System:** Linux 5.10.39-gnu-1-lts x86_64 GNU/Linux
* **Python:** 3.9.5

**Comment by adbenitez** [comment]
>     * **Python:** 3.9.5

it is this, there are no deltachat wheels for python 3.9 on pypi.org, check: https://pypi.org/project/deltachat/#files

but you are lucky, there are python 3.9 wheels created recently, to install it run:

```
pip install --pre -U -i https://m.devpi.net/dc/master deltachat
```

then you can install deltachat-cursed:

```
pip install deltachat-cursed
```

**Comment by LeMeteore** [comment]
I would like to help. Any idea on how to ease the installation for the user? Should we find a ways to correctly find & install the good DeltaChat wheels, then install DeltaChat-cursed?

**Comment by adbenitez** [comment]
this is an old issue, forgot to close it, there is already wheels for python 3.9 in PyPI, check: https://pypi.org/project/deltachat/#files (3.7 , 3.8 and 3.9 are supported)

@LeMeteore  thanks for the interest, you are welcome to help.

about your question, it is just to `pip install deltachat-cursed` that sounds easy enough :)

**Comment by LeMeteore** [comment]
> thanks for the interest, you are welcome to help in other issues. 

I'll browse the other issues and see if there is one I can tackle.

**Comment by adbenitez** [comment]
also if there is something you think that should be improved or added, you are free to open new issues and tackle the things you are interested in ;)
