### ISSUE TITLE
PackageNotFoundError: deltachat not found

### ISSUE THREAD

**Issue by jose1711** [adbenitez/deltachat-cursed#53]
Trying to install the program I got:
```
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      Traceback (most recent call last):
        File "/home/jose/deltachat/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/jose/deltachat/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/jose/deltachat/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-d4mrgvpu/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 188, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-d4mrgvpu/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 39, in <module>
          main()
        File "setup.py", line 9, in main
          setuptools.setup(
        File "/tmp/pip-build-env-d4mrgvpu/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-d4mrgvpu/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-d4mrgvpu/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 477, in __init__
          _Distribution.__init__(
        File "/tmp/pip-build-env-d4mrgvpu/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-d4mrgvpu/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 901, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-d4mrgvpu/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 922, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-build-env-d4mrgvpu/overlay/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
          add_cffi_module(dist, cffi_module)
        File "/tmp/pip-build-env-d4mrgvpu/overlay/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 57, in add_cffi_module
          ffi = ffi()      # maybe it's a function instead of directly an ffi
        File "src/deltachat/_build.py", line 170, in ffibuilder
          flags = system_build_flags()
        File "src/deltachat/_build.py", line 46, in system_build_flags
          return pkgconfig.parse('deltachat')
        File "/tmp/pip-build-env-d4mrgvpu/overlay/lib/python3.10/site-packages/pkgconfig/pkgconfig.py", line 248, in parse
          _raise_if_not_exists(package)
        File "/tmp/pip-build-env-d4mrgvpu/overlay/lib/python3.10/site-packages/pkgconfig/pkgconfig.py", line 103, in _raise_if_not_exists
          raise PackageNotFoundError(package)
      pkgconfig.pkgconfig.PackageNotFoundError: deltachat not found
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Arch Linux x86_64, python 3.10.4

**Comment by dotlambda** [comment]
You need to install libdeltachat: https://github.com/deltachat/deltachat-core-rust#installing-libdeltachat-system-wide

**Comment by adbenitez** [comment]
hi @jose1711 the issue is that simplebot depends on [deltachat package](https://pypi.org/project/deltachat/#files) which as you can see in that link, it doesn't offers wheels for python 10 at the moment, I am talking with the package maintainers to see if they can provide support for python 10 so you could install it normally without having to compile the `deltachat` package yourself

**Comment by adbenitez** [comment]
for now what you can do is to build the package yourself following this instructions:
https://pypi.org/project/deltachat/#sourceinstall

or installing python 9 in your system and using that to install simplebot

**Comment by jose1711** [comment]
Thank you both, all is good now.

**Comment by dotlambda** [comment]
What did you end up doing?

**Comment by jose1711** [comment]
> What did you end up doing?

The crucial part was installation of `libdeltachat`. Anyway Arch Linux users can find this program in AUR now (https://aur.archlinux.org/packages/python-deltachat-cursed) so installation should be a matter of running:
```
yay -S python-deltachat-cursed
```
It will take care of getting all the dependency, building and installing.

**Comment by dotlambda** [comment]
@jose1711 Are you in one of the developer groups on Delta Chat? I have some comments on your AUR packages.

**Comment by jose1711** [comment]
> @jose1711 Are you in one of the developer groups on Delta Chat? I have some comments on your AUR packages.

No I am not. I appreciate any feedback - be it here, in AUR comments or in private chat.
